#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OnSoil.Resource", IsApplication=true)]

namespace OnSoil
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0
			public static int slide_in_top = 0;
			
			// aapt resource value: 0
			public static int slide_in_topBACK = 0;
			
			// aapt resource value: 0
			public static int slide_out = 0;
			
			// aapt resource value: 0
			public static int slide_out_bottomBACK = 0;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0
			public static int botSoil = 0;
			
			// aapt resource value: 0
			public static int botSoil1 = 0;
			
			// aapt resource value: 0
			public static int botSoilTest = 0;
			
			// aapt resource value: 0
			public static int Icon = 0;
			
			// aapt resource value: 0
			public static int TopSoil = 0;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0
			public static int AddProfileButton = 0;
			
			// aapt resource value: 0
			public static int ConfirmButton = 0;
			
			// aapt resource value: 0
			public static int CounterText = 0;
			
			// aapt resource value: 0
			public static int delProfButton = 0;
			
			// aapt resource value: 0
			public static int DiaryButton = 0;
			
			// aapt resource value: 0
			public static int diarySoilsTextView = 0;
			
			// aapt resource value: 0
			public static int EasyGameButton = 0;
			
			// aapt resource value: 0
			public static int ExitButton = 0;
			
			// aapt resource value: 0
			public static int GameButton = 0;
			
			// aapt resource value: 0
			public static int GardenTextView = 0;
			
			// aapt resource value: 0
			public static int HardGameButton = 0;
			
			// aapt resource value: 0
			public static int HintButton = 0;
			
			// aapt resource value: 0
			public static int horAcidLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horAcidSpinner = 0;
			
			// aapt resource value: 0
			public static int horAcidTextView = 0;
			
			// aapt resource value: 0
			public static int horBioNeoplasmsLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horBioNeoplasmsSpinner = 0;
			
			// aapt resource value: 0
			public static int horBioNeoplasmsTextView = 0;
			
			// aapt resource value: 0
			public static int horColorEditText = 0;
			
			// aapt resource value: 0
			public static int horColorLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horColorTextView = 0;
			
			// aapt resource value: 0
			public static int horCommentEditText = 0;
			
			// aapt resource value: 0
			public static int horCommentLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horCommentTextView = 0;
			
			// aapt resource value: 0
			public static int horCompositionLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horCompositionSpinner = 0;
			
			// aapt resource value: 0
			public static int horCompositionTextView = 0;
			
			// aapt resource value: 0
			public static int horDeleteButton = 0;
			
			// aapt resource value: 0
			public static int horDensityLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horDensitySpinner = 0;
			
			// aapt resource value: 0
			public static int horDensityTextView = 0;
			
			// aapt resource value: 0
			public static int horIncludeEditText = 0;
			
			// aapt resource value: 0
			public static int horIncludeLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horIncludeTextView = 0;
			
			// aapt resource value: 0
			public static int HorizonsButton = 0;
			
			// aapt resource value: 0
			public static int HorizontName1 = 0;
			
			// aapt resource value: 0
			public static int HorizontName2 = 0;
			
			// aapt resource value: 0
			public static int HorizontName3 = 0;
			
			// aapt resource value: 0
			public static int HorizontName4 = 0;
			
			// aapt resource value: 0
			public static int HorizontName5 = 0;
			
			// aapt resource value: 0
			public static int HorizontName6 = 0;
			
			// aapt resource value: 0
			public static int HorizontName7 = 0;
			
			// aapt resource value: 0
			public static int horKutansEditText = 0;
			
			// aapt resource value: 0
			public static int horKutansLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horKutansTextView = 0;
			
			// aapt resource value: 0
			public static int horLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horNameEditText = 0;
			
			// aapt resource value: 0
			public static int horNamelinearLayout = 0;
			
			// aapt resource value: 0
			public static int horNametextView = 0;
			
			// aapt resource value: 0
			public static int horOrgTypeEditText = 0;
			
			// aapt resource value: 0
			public static int horOrgTypeLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horOrgTypeTextView = 0;
			
			// aapt resource value: 0
			public static int horPoreLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horPoreSpinner = 0;
			
			// aapt resource value: 0
			public static int horPoreTextView = 0;
			
			// aapt resource value: 0
			public static int horSaveButton = 0;
			
			// aapt resource value: 0
			public static int horScrollView = 0;
			
			// aapt resource value: 0
			public static int horStretchingEditText = 0;
			
			// aapt resource value: 0
			public static int horStretchingLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horStretchingTextView = 0;
			
			// aapt resource value: 0
			public static int horStructLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horStructSpinner = 0;
			
			// aapt resource value: 0
			public static int horStructTextView = 0;
			
			// aapt resource value: 0
			public static int horTiltelinearLayout = 0;
			
			// aapt resource value: 0
			public static int horTitleView = 0;
			
			// aapt resource value: 0
			public static int horWetLinearLayout = 0;
			
			// aapt resource value: 0
			public static int horWetSpinner = 0;
			
			// aapt resource value: 0
			public static int horWetTextView = 0;
			
			// aapt resource value: 0
			public static int linearLayout1 = 0;
			
			// aapt resource value: 0
			public static int linearLayout2 = 0;
			
			// aapt resource value: 0
			public static int linearLayout3 = 0;
			
			// aapt resource value: 0
			public static int linearLayout4 = 0;
			
			// aapt resource value: 0
			public static int linearLayout5 = 0;
			
			// aapt resource value: 0
			public static int linearLayout6 = 0;
			
			// aapt resource value: 0
			public static int linearLayoutFor = 0;
			
			// aapt resource value: 0
			public static int ListItemButtonsLayout = 0;
			
			// aapt resource value: 0
			public static int ListItemDelete = 0;
			
			// aapt resource value: 0
			public static int ListItemEdit = 0;
			
			// aapt resource value: 0
			public static int ListItemName = 0;
			
			// aapt resource value: 0
			public static int ListItemRead = 0;
			
			// aapt resource value: 0
			public static int ListView = 0;
			
			// aapt resource value: 0
			public static int listViewWithSoils = 0;
			
			// aapt resource value: 0
			public static int mainLinearLayout = 0;
			
			// aapt resource value: 0
			public static int myGarden = 0;
			
			// aapt resource value: 0
			public static int profAddHorButton = 0;
			
			// aapt resource value: 0
			public static int profButtonsLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profCommentaryEditText = 0;
			
			// aapt resource value: 0
			public static int profCommentarylinearLayout16 = 0;
			
			// aapt resource value: 0
			public static int profCommentaryTextView = 0;
			
			// aapt resource value: 0
			public static int profDateLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profDatePicker = 0;
			
			// aapt resource value: 0
			public static int profDelHorButton = 0;
			
			// aapt resource value: 0
			public static int profEditHorButton = 0;
			
			// aapt resource value: 0
			public static int profGeoLocEditText = 0;
			
			// aapt resource value: 0
			public static int profGeoLocLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profGeoLocTextView = 0;
			
			// aapt resource value: 0
			public static int profHorLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profHorSpinner = 0;
			
			// aapt resource value: 0
			public static int profHorTextView = 0;
			
			// aapt resource value: 0
			public static int profHydroEditText = 0;
			
			// aapt resource value: 0
			public static int profHydroLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profHydroTextView = 0;
			
			// aapt resource value: 0
			public static int ProfilesButton = 0;
			
			// aapt resource value: 0
			public static int profNameEditText = 0;
			
			// aapt resource value: 0
			public static int profNameLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profNameTextView = 0;
			
			// aapt resource value: 0
			public static int profNumberEditText = 0;
			
			// aapt resource value: 0
			public static int profNumberLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profNumberTextView = 0;
			
			// aapt resource value: 0
			public static int profReliefEditText = 0;
			
			// aapt resource value: 0
			public static int profReliefLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profReliefTextView = 0;
			
			// aapt resource value: 0
			public static int profScrollView = 0;
			
			// aapt resource value: 0
			public static int profSiteEditText = 0;
			
			// aapt resource value: 0
			public static int profSiteLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profSiteTextView = 0;
			
			// aapt resource value: 0
			public static int profSurfaceLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profSurfaceSpinner = 0;
			
			// aapt resource value: 0
			public static int profSurfaceTextView = 0;
			
			// aapt resource value: 0
			public static int profTitleLayout = 0;
			
			// aapt resource value: 0
			public static int profTitleView = 0;
			
			// aapt resource value: 0
			public static int profTopBindEditText = 0;
			
			// aapt resource value: 0
			public static int profTopBindLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profTopBindTextView = 0;
			
			// aapt resource value: 0
			public static int profVegetationEditText = 0;
			
			// aapt resource value: 0
			public static int profVegetationLinearLayout = 0;
			
			// aapt resource value: 0
			public static int profVegetationTextView = 0;
			
			// aapt resource value: 0
			public static int progressBar1 = 0;
			
			// aapt resource value: 0
			public static int recordText = 0;
			
			// aapt resource value: 0
			public static int saveProfButton = 0;
			
			// aapt resource value: 0
			public static int scrollView1 = 0;
			
			// aapt resource value: 0
			public static int SoilName = 0;
			
			// aapt resource value: 0
			public static int SoilVersion = 0;
			
			// aapt resource value: 0
			public static int spinner1 = 0;
			
			// aapt resource value: 0
			public static int spinner2 = 0;
			
			// aapt resource value: 0
			public static int spinner3 = 0;
			
			// aapt resource value: 0
			public static int spinner4 = 0;
			
			// aapt resource value: 0
			public static int spinner5 = 0;
			
			// aapt resource value: 0
			public static int spinner6 = 0;
			
			// aapt resource value: 0
			public static int spinner7 = 0;
			
			// aapt resource value: 0
			public static int tableLayout1 = 0;
			
			// aapt resource value: 0
			public static int tableRow1 = 0;
			
			// aapt resource value: 0
			public static int tableRow2 = 0;
			
			// aapt resource value: 0
			public static int tableRow3 = 0;
			
			// aapt resource value: 0
			public static int tableRow4 = 0;
			
			// aapt resource value: 0
			public static int tableRow5 = 0;
			
			// aapt resource value: 0
			public static int tableRow6 = 0;
			
			// aapt resource value: 0
			public static int tableRow7 = 0;
			
			// aapt resource value: 0
			public static int textLinearLayout = 0;
			
			// aapt resource value: 0
			public static int TextView = 0;
			
			// aapt resource value: 0
			public static int textView1 = 0;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0
			public static int Diary = 0;
			
			// aapt resource value: 0
			public static int Directory = 0;
			
			// aapt resource value: 0
			public static int FillGame = 0;
			
			// aapt resource value: 0
			public static int FillGameEnd = 0;
			
			// aapt resource value: 0
			public static int FillingHoriz = 0;
			
			// aapt resource value: 0
			public static int FillingInfo = 0;
			
			// aapt resource value: 0
			public static int GameList = 0;
			
			// aapt resource value: 0
			public static int Garden = 0;
			
			// aapt resource value: 0
			public static int Main = 0;
			
			// aapt resource value: 0
			public static int MyListItem = 0;
			
			// aapt resource value: 0
			public static int Record = 0;
			
			// aapt resource value: 0
			public static int SoilsInfo = 0;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0
			public static int ApplicationName = 0;
			
			// aapt resource value: 0
			public static int Hello = 0;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
