#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("OnSoil.Resource", IsApplication=true)]

namespace OnSoil
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_top = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_topBACK = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_bottomBACK = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int botSoil = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int botSoil1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int botSoilTest = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int TopSoil = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int AddProfileButton = 2131099650;
			
			// aapt resource value: 0x7f06001e
			public const int ConfirmButton = 2131099678;
			
			// aapt resource value: 0x7f06000f
			public const int CounterText = 2131099663;
			
			// aapt resource value: 0x7f06008b
			public const int DiaryButton = 2131099787;
			
			// aapt resource value: 0x7f060084
			public const int EasyGameButton = 2131099780;
			
			// aapt resource value: 0x7f06008f
			public const int ExitButton = 2131099791;
			
			// aapt resource value: 0x7f060088
			public const int GameButton = 2131099784;
			
			// aapt resource value: 0x7f060087
			public const int GardenTextView = 2131099783;
			
			// aapt resource value: 0x7f060085
			public const int HardGameButton = 2131099781;
			
			// aapt resource value: 0x7f060089
			public const int HintButton = 2131099785;
			
			// aapt resource value: 0x7f060007
			public const int HorizonsButton = 2131099655;
			
			// aapt resource value: 0x7f060020
			public const int HorizontName1 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int HorizontName2 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int HorizontName3 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int HorizontName4 = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int HorizontName5 = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int HorizontName6 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int HorizontName7 = 2131099686;
			
			// aapt resource value: 0x7f060091
			public const int ListItemButtonsLayout = 2131099793;
			
			// aapt resource value: 0x7f060093
			public const int ListItemDelete = 2131099795;
			
			// aapt resource value: 0x7f060092
			public const int ListItemEdit = 2131099794;
			
			// aapt resource value: 0x7f060090
			public const int ListItemName = 2131099792;
			
			// aapt resource value: 0x7f060094
			public const int ListItemRead = 2131099796;
			
			// aapt resource value: 0x7f060096
			public const int ListView = 2131099798;
			
			// aapt resource value: 0x7f06000a
			public const int ProfilesButton = 2131099658;
			
			// aapt resource value: 0x7f060011
			public const int SoilName = 2131099665;
			
			// aapt resource value: 0x7f06000d
			public const int SoilVersion = 2131099661;
			
			// aapt resource value: 0x7f060095
			public const int TextView = 2131099797;
			
			// aapt resource value: 0x7f060083
			public const int delProfButton = 2131099779;
			
			// aapt resource value: 0x7f060004
			public const int diarySoilsTextView = 2131099652;
			
			// aapt resource value: 0x7f06004f
			public const int horAcidLinearLayout = 2131099727;
			
			// aapt resource value: 0x7f060051
			public const int horAcidSpinner = 2131099729;
			
			// aapt resource value: 0x7f060050
			public const int horAcidTextView = 2131099728;
			
			// aapt resource value: 0x7f060049
			public const int horBioNeoplasmsLinearLayout = 2131099721;
			
			// aapt resource value: 0x7f06004b
			public const int horBioNeoplasmsSpinner = 2131099723;
			
			// aapt resource value: 0x7f06004a
			public const int horBioNeoplasmsTextView = 2131099722;
			
			// aapt resource value: 0x7f060030
			public const int horColorEditText = 2131099696;
			
			// aapt resource value: 0x7f06002e
			public const int horColorLinearLayout = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int horColorTextView = 2131099695;
			
			// aapt resource value: 0x7f060054
			public const int horCommentEditText = 2131099732;
			
			// aapt resource value: 0x7f060052
			public const int horCommentLinearLayout = 2131099730;
			
			// aapt resource value: 0x7f060053
			public const int horCommentTextView = 2131099731;
			
			// aapt resource value: 0x7f060034
			public const int horCompositionLinearLayout = 2131099700;
			
			// aapt resource value: 0x7f060036
			public const int horCompositionSpinner = 2131099702;
			
			// aapt resource value: 0x7f060035
			public const int horCompositionTextView = 2131099701;
			
			// aapt resource value: 0x7f060056
			public const int horDeleteButton = 2131099734;
			
			// aapt resource value: 0x7f06003d
			public const int horDensityLinearLayout = 2131099709;
			
			// aapt resource value: 0x7f06003f
			public const int horDensitySpinner = 2131099711;
			
			// aapt resource value: 0x7f06003e
			public const int horDensityTextView = 2131099710;
			
			// aapt resource value: 0x7f06004e
			public const int horIncludeEditText = 2131099726;
			
			// aapt resource value: 0x7f06004c
			public const int horIncludeLinearLayout = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int horIncludeTextView = 2131099725;
			
			// aapt resource value: 0x7f060045
			public const int horKutansEditText = 2131099717;
			
			// aapt resource value: 0x7f060043
			public const int horKutansLinearLayout = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int horKutansTextView = 2131099716;
			
			// aapt resource value: 0x7f060028
			public const int horLinearLayout = 2131099688;
			
			// aapt resource value: 0x7f06002d
			public const int horNameEditText = 2131099693;
			
			// aapt resource value: 0x7f06002b
			public const int horNamelinearLayout = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int horNametextView = 2131099692;
			
			// aapt resource value: 0x7f06003c
			public const int horOrgTypeEditText = 2131099708;
			
			// aapt resource value: 0x7f06003a
			public const int horOrgTypeLinearLayout = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int horOrgTypeTextView = 2131099707;
			
			// aapt resource value: 0x7f060040
			public const int horPoreLinearLayout = 2131099712;
			
			// aapt resource value: 0x7f060042
			public const int horPoreSpinner = 2131099714;
			
			// aapt resource value: 0x7f060041
			public const int horPoreTextView = 2131099713;
			
			// aapt resource value: 0x7f060055
			public const int horSaveButton = 2131099733;
			
			// aapt resource value: 0x7f060027
			public const int horScrollView = 2131099687;
			
			// aapt resource value: 0x7f060048
			public const int horStretchingEditText = 2131099720;
			
			// aapt resource value: 0x7f060046
			public const int horStretchingLinearLayout = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int horStretchingTextView = 2131099719;
			
			// aapt resource value: 0x7f060031
			public const int horStructLinearLayout = 2131099697;
			
			// aapt resource value: 0x7f060033
			public const int horStructSpinner = 2131099699;
			
			// aapt resource value: 0x7f060032
			public const int horStructTextView = 2131099698;
			
			// aapt resource value: 0x7f060029
			public const int horTiltelinearLayout = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int horTitleView = 2131099690;
			
			// aapt resource value: 0x7f060037
			public const int horWetLinearLayout = 2131099703;
			
			// aapt resource value: 0x7f060039
			public const int horWetSpinner = 2131099705;
			
			// aapt resource value: 0x7f060038
			public const int horWetTextView = 2131099704;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout1 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int linearLayout2 = 2131099660;
			
			// aapt resource value: 0x7f06001d
			public const int linearLayout3 = 2131099677;
			
			// aapt resource value: 0x7f06008a
			public const int linearLayout4 = 2131099786;
			
			// aapt resource value: 0x7f06008c
			public const int linearLayout5 = 2131099788;
			
			// aapt resource value: 0x7f06008e
			public const int linearLayout6 = 2131099790;
			
			// aapt resource value: 0x7f060081
			public const int linearLayoutFor = 2131099777;
			
			// aapt resource value: 0x7f060001
			public const int listViewWithSoils = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int mainLinearLayout = 2131099648;
			
			// aapt resource value: 0x7f06008d
			public const int myGarden = 2131099789;
			
			// aapt resource value: 0x7f06007e
			public const int profAddHorButton = 2131099774;
			
			// aapt resource value: 0x7f06007d
			public const int profButtonsLinearLayout = 2131099773;
			
			// aapt resource value: 0x7f060079
			public const int profCommentaryEditText = 2131099769;
			
			// aapt resource value: 0x7f060078
			public const int profCommentaryTextView = 2131099768;
			
			// aapt resource value: 0x7f060077
			public const int profCommentarylinearLayout16 = 2131099767;
			
			// aapt resource value: 0x7f06005a
			public const int profDateLinearLayout = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int profDatePicker = 2131099739;
			
			// aapt resource value: 0x7f06007f
			public const int profDelHorButton = 2131099775;
			
			// aapt resource value: 0x7f060080
			public const int profEditHorButton = 2131099776;
			
			// aapt resource value: 0x7f060064
			public const int profGeoLocEditText = 2131099748;
			
			// aapt resource value: 0x7f060062
			public const int profGeoLocLinearLayout = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int profGeoLocTextView = 2131099747;
			
			// aapt resource value: 0x7f06007a
			public const int profHorLinearLayout = 2131099770;
			
			// aapt resource value: 0x7f06007c
			public const int profHorSpinner = 2131099772;
			
			// aapt resource value: 0x7f06007b
			public const int profHorTextView = 2131099771;
			
			// aapt resource value: 0x7f060073
			public const int profHydroEditText = 2131099763;
			
			// aapt resource value: 0x7f060071
			public const int profHydroLinearLayout = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int profHydroTextView = 2131099762;
			
			// aapt resource value: 0x7f060061
			public const int profNameEditText = 2131099745;
			
			// aapt resource value: 0x7f06005f
			public const int profNameLinearLayout = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int profNameTextView = 2131099744;
			
			// aapt resource value: 0x7f06005e
			public const int profNumberEditText = 2131099742;
			
			// aapt resource value: 0x7f06005c
			public const int profNumberLinearLayout = 2131099740;
			
			// aapt resource value: 0x7f06005d
			public const int profNumberTextView = 2131099741;
			
			// aapt resource value: 0x7f06006a
			public const int profReliefEditText = 2131099754;
			
			// aapt resource value: 0x7f060068
			public const int profReliefLinearLayout = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int profReliefTextView = 2131099753;
			
			// aapt resource value: 0x7f060057
			public const int profScrollView = 2131099735;
			
			// aapt resource value: 0x7f06006d
			public const int profSiteEditText = 2131099757;
			
			// aapt resource value: 0x7f06006b
			public const int profSiteLinearLayout = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int profSiteTextView = 2131099756;
			
			// aapt resource value: 0x7f060074
			public const int profSurfaceLinearLayout = 2131099764;
			
			// aapt resource value: 0x7f060076
			public const int profSurfaceSpinner = 2131099766;
			
			// aapt resource value: 0x7f060075
			public const int profSurfaceTextView = 2131099765;
			
			// aapt resource value: 0x7f060058
			public const int profTitleLayout = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int profTitleView = 2131099737;
			
			// aapt resource value: 0x7f060067
			public const int profTopBindEditText = 2131099751;
			
			// aapt resource value: 0x7f060065
			public const int profTopBindLinearLayout = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int profTopBindTextView = 2131099750;
			
			// aapt resource value: 0x7f060070
			public const int profVegetationEditText = 2131099760;
			
			// aapt resource value: 0x7f06006e
			public const int profVegetationLinearLayout = 2131099758;
			
			// aapt resource value: 0x7f06006f
			public const int profVegetationTextView = 2131099759;
			
			// aapt resource value: 0x7f060010
			public const int progressBar1 = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int recordText = 2131099662;
			
			// aapt resource value: 0x7f060082
			public const int saveProfButton = 2131099778;
			
			// aapt resource value: 0x7f060086
			public const int scrollView1 = 2131099782;
			
			// aapt resource value: 0x7f060012
			public const int spinner1 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int spinner2 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int spinner3 = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int spinner4 = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int spinner5 = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int spinner6 = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int spinner7 = 2131099676;
			
			// aapt resource value: 0x7f060005
			public const int tableLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int tableRow1 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int tableRow2 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int tableRow3 = 2131099657;
			
			// aapt resource value: 0x7f060015
			public const int tableRow4 = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int tableRow5 = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int tableRow6 = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int tableRow7 = 2131099675;
			
			// aapt resource value: 0x7f060003
			public const int textLinearLayout = 2131099651;
			
			// aapt resource value: 0x7f06001f
			public const int textView1 = 2131099679;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Diary = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Directory = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FillGame = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int FillGameEnd = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FillingHoriz = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int FillingInfo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int GameList = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Garden = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int MyListItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Record = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int SoilsInfo = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int action_settings = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
